### ISSUE TITLE
fact_table references inexistent data.

### ISSUE THREAD

**Issue by rishabh-bhatnagar** [bhushan-borole/dwm-pracs#1]
https://github.com/bhushan-borole/dwm-pracs/blob/master/olap/super_market.sql in this file, while inserting data in the fact_table, insertion is made for foreign keys of id's of some dimension table which is not a primary key for the dimension table.  
For example: `insert into store_fact_table values(1, 3, 1, 4);` this is line 48 of [223f3dd](https://github.com/bhushan-borole/dwm-pracs/commit/223f3dd0e6c691d5ac8ec24da4627793c74633db) commit.   
This will try inserting store_id=3 which is not present in store_dim table.

**Comment by bhushan-borole** [comment]
30f3395
This commit will resolve this issue.
